"""Pure caption logic: transcript reshaping, ffmpeg escaping, filter assembly.

Captions cost nothing beyond what the pipeline already pays for. The word-level
timings come from phase 2's transcription, which has already been billed, and
the burn-in is libass inside the ffmpeg pass that was going to run anyway — no
third service, no per-clip fee, nothing that phones home.

The ASS document itself is generated by the host repository's
``clippyme.domain.subtitles.generate_ass_karaoke``: 800-odd lines that already
handle ``\\k`` karaoke timing, six presets, per-preset styling, and — the part
worth not re-deriving — semantic line breaking, so a caption never straddles a
full stop. That module is stdlib-only at import time, so reusing it costs no
extra dependency either.

What lives here is the join between that and phase 6: converting
:class:`~clipper_pro.types.Word` into the shape it expects, and escaping the
resulting path safely into a filtergraph.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Any

from clipper_pro.errors import ValidationError
from clipper_pro.types import Word

__all__ = [
    "CAPTION_POSITIONS",
    "CAPTION_PRESETS",
    "DEFAULT_FONT_SCALE",
    "CaptionSettings",
    "build_ass_filter",
    "escape_filter_value",
    "resolve_font_size",
    "scaled_font_size",
    "words_to_transcript",
]

#: Style presets, mirroring ``clippyme.domain.subtitles.SUBTITLE_PRESETS``.
#: Listed explicitly rather than imported so a UI can offer them without
#: pulling the subtitle module in, and so an unknown name fails here with a
#: clear message instead of silently falling back to the default preset.
CAPTION_PRESETS: tuple[str, ...] = (
    "hormozi_bold",
    "classic_white",
    "neon_glow",
    "mrbeast_box",
    "minimal_clean",
    "fire_impact",
)

CAPTION_POSITIONS: tuple[str, ...] = ("bottom", "center", "top")

#: Words shown at once. Three is the short-form convention: enough to read in a
#: glance, few enough that the highlight lands on the word being said.
DEFAULT_WORDS_PER_GROUP = 3

#: Multiplier applied to a preset's own font size.
#:
#: The host repository's presets are sized 52-64 against a 1920-tall frame —
#: about 3% of frame height, which is a readable *subtitle* but not the
#: scroll-stopping caption these presets are named after. Short-form captions
#: sit nearer 5-6%. Scaling rather than overriding keeps each preset's relative
#: proportions (minimal_clean stays smaller than fire_impact) instead of
#: flattening six designs onto one number.
#:
#: Tracks the host presets: they were 35-43 (~2%) against a 2.4 scale, and
#: were raised ~1.5x, so this drops by the same ratio. The DELIVERED caption
#: size here is what the ~5-6% target fixes — it must not move just because
#: the shared base did.
DEFAULT_FONT_SCALE = 1.6


@dataclass(frozen=True)
class CaptionSettings:
    """How captions should look. Validated on construction."""

    enabled: bool = False
    preset: str = "hormozi_bold"
    words_per_group: int = DEFAULT_WORDS_PER_GROUP
    position: str = "bottom"
    uppercase: bool = True
    #: Absolute size, overriding the preset-and-scale calculation entirely.
    font_size: int | None = None
    scale: float = DEFAULT_FONT_SCALE

    def __post_init__(self) -> None:
        if self.preset not in CAPTION_PRESETS:
            raise ValidationError(
                f"unknown caption preset {self.preset!r} — "
                f"expected one of {', '.join(CAPTION_PRESETS)}"
            )
        if self.position not in CAPTION_POSITIONS:
            raise ValidationError(
                f"unknown caption position {self.position!r} — "
                f"expected one of {', '.join(CAPTION_POSITIONS)}"
            )
        if not 1 <= self.words_per_group <= 12:
            raise ValidationError(
                f"words_per_group must be within 1–12, got {self.words_per_group}"
            )
        if self.font_size is not None and not 10 <= self.font_size <= 400:
            raise ValidationError(
                f"font_size must be within 10–400, got {self.font_size}"
            )
        if not 0.2 <= self.scale <= 8.0:
            raise ValidationError(f"scale must be within 0.2–8.0, got {self.scale}")


def scaled_font_size(base: int, scale: float) -> int:
    """A preset's base size scaled into the short-form range, clamped to sanity."""
    return max(10, min(400, round(base * scale)))


def preset_base_font_size(preset: str) -> int | None:
    """The host repository's own size for ``preset``, or ``None`` if unknown."""
    try:
        from clippyme.domain.subtitles import SUBTITLE_PRESETS
    except ImportError:  # pragma: no cover - stdlib-only module
        return None
    entry = SUBTITLE_PRESETS.get(preset)
    size = entry.get("fontsize") if isinstance(entry, dict) else None
    return int(size) if isinstance(size, (int, float)) else None


def resolve_font_size(settings: CaptionSettings) -> int | None:
    """The size to hand the generator: explicit override, else preset x scale."""
    if settings.font_size is not None:
        return settings.font_size
    base = preset_base_font_size(settings.preset)
    return scaled_font_size(base, settings.scale) if base else None


def words_to_transcript(words: list[Word]) -> dict[str, Any]:
    """Render words in the transcript shape ``generate_ass_karaoke`` expects.

    That function reads ``transcript['segments'][*]['words'][*]`` with ``word``
    / ``start`` / ``end`` keys. One segment holding everything is correct here:
    the karaoke grouper re-splits the stream on its own semantic boundaries, so
    pre-segmenting would only impose breaks it did not choose.
    """
    return {
        "segments": [
            {
                "words": [
                    {"word": w.text, "start": w.start, "end": w.end} for w in words
                ]
            }
        ]
    }


def escape_filter_value(value: str) -> str:
    """Escape a path for use as an ffmpeg filter option value.

    The filtergraph parser treats ``\\``, ``:``, and ``'`` as structure — a
    colon separates one option from the next — so a path containing any of them
    would silently split into nonsense options rather than failing loudly.
    Backslash goes first: escaping it after the others would double the escapes
    they just introduced.
    """
    return value.replace("\\", "\\\\").replace(":", "\\:").replace("'", "\\'")


def build_ass_filter(ass_path: str, fonts_dir: str | None = None) -> str:
    """The ``ass=`` filter that burns ``ass_path`` into the frame.

    Placed last in phase 6's chain, *after* crop and scale, because the ASS
    document declares ``PlayResX/Y`` of 1080x1920 — the delivery frame. Burning
    before the scale would render the captions against the crop's pixel
    dimensions and then resample them, leaving text that is both mispositioned
    and soft.
    """
    if not ass_path:
        raise ValidationError("cannot build a caption filter without a subtitle file")

    parts = [f"ass=f={escape_filter_value(ass_path)}"]
    if fonts_dir:
        # Without this libass resolves font names against system fonts only, and
        # the bundled display faces (Anton, Montserrat Black) would silently
        # fall back to whatever fontconfig picks — usually a plain sans.
        parts.append(f"fontsdir={escape_filter_value(fonts_dir)}")
    return ":".join(parts)


def bundled_fonts_dir() -> str | None:
    """The host repository's bundled font directory, if it is present."""
    try:
        from clippyme.domain.subtitles import FONTS_DIR
    except ImportError:  # pragma: no cover - stdlib-only module, always present
        return None
    return FONTS_DIR if FONTS_DIR and os.path.isdir(FONTS_DIR) else None
